# OpenGL-Bunny
* Recent Notes
Hey guys, I wrote some code for parsing and reading in the data and making the
bunny show. Also split up the program into different files so we can all work on
different things at the same time without interfering with each other.

Also, I added a Makefile. In order to run just type

#+BEGIN_SRC python
Compy:~/Desktop/OpenGL-Bunny[0] make
gcc -L/usr/lib64 -O2 -Wall -c main.c -o main.o
gcc -L/usr/lib64 -O2 -Wall -c drawStuff.c -o drawStuff.o
gcc -L/usr/lib64 -O2 -Wall -c lighting.c -o lighting.o
gcc -L/usr/lib64 -O2 -Wall -c material.c -o material.o
gcc -L/usr/lib64 -O2 -Wall -c parser.c -o parser.o
gcc -L/usr/lib64 -O2 -Wall -c viewVolume.c -o viewVolume.o
gcc -L/usr/lib64 -O2 -Wall -o run main.o drawStuff.o lighting.o material.o parser.o viewVolume.o -lX11 -lGL -lGLU -lglut -lm -lXmu -lXi -lm

Compy:~/Desktop/OpenGL-Bunny[1] ./run
min(x,y,z) = (-0.094690,0.000000,-0.061874)
max(x,y,z) = (0.061009,0.187321,0.058800)
#+END_SRC

The min and max x,y,z values are just showing the position of the bunny in 3d space.
Also, please run make clean before committing changes

#+BEGIN_SRC python
Compy:~/Desktop/OpenGL-Bunny[2] make clean
rm -rf main.o drawStuff.o lighting.o material.o parser.o viewVolume.o
rm -rf run
#+END_SRC


* OpenGL-Bunny
Stanford Bunny with OpenGL

** Our Todo list
- Change lighting and colors to be used
  - This is to be done in lighting.c
- Change material, things like shininess.
  - To be done in material.c
- Fix the view volumes up direction
  - To be done in viewVolume.c
- Maybe apply transform to bunny to rotate to a better viewing angle
  - To be done in drawStuff.c
- We must implement one of the following features as well.
  - Motion-blur
  - Depth of Field
  - Textures
  - Shadows
  - A user interface with selectable eye point and view direction.

** Our done list
- Parsing
- Basic drawStuff layout

** Contributors
/Kylon Tyner/,
/Connor Kinzie/,
/Ryland Bristow/,
/Angelo Carrabba/
