# OpenGL-Bunny
* Recent Notes
Hey guys, I wrote some code for parsing and reading in the data and making the
bunny show. Also split up the program into different files so we can all work on
different things at the same time without interfering with each other.

Also, I added a Makefile. In order to run just type

#+BEGIN_SRC bash
make
./run
#+END_SRC

* OpenGL-Bunny
Stanford Bunny with OpenGL

* Our Todo list
** TODO Change lighting and colors to be used
   This is to be done in lighting.c
** TODO Change material, things like shininess.
   To be done in material.c
** TODO Fix the view volumes up direction
   To be done in viewVolume.c
** TODO Maybe apply transform to bunny to rotate to a better viewing angle
   To be done in drawStuff.c

*** We must implement one of the following features as well.
- Motion-blur
- Depth of Field
- Textures
- Shadows
- A user interface with selectable eye point and view direction.

* Our done list
** DONE Parsing
   CLOSED: [2017-02-13 Mon 19:34]
** DONE Basic drawStuff layout
   CLOSED: [2017-02-13 Mon 19:35]

* Contributors
/Kylon Tyner/,
/Connor Kinzie/,
/Ryland Bristow/,
/Angelo Carrabba/
